from dataclasses import dataclass
from typing import Optional

@dataclass
class PromptTemplate:
    name: str
    template: str
    version: Optional[str] = None
    description: Optional[str] = None

# Then define your prompts
PROMPT_1 = PromptTemplate(
    name="basic_classification",
    template="""You are given the source code of a generative artwork (sound, visual, or textual).  
    Using the framework below, tag the artwork along 3 dimensions.

    1) Entities  
    Select all that apply:
    - processed audio        // uses existing audio (e.g., mp3, wav, midi)
    - processed image        // uses existing visual media (e.g., images, video)
    - processed text         // uses existing text/code files
    - synthesized sound      // generates new sounds or notes
    - synthesized image      // generates new visual elements
    - synthesized text       // generates new textual or typographic elements
    - randomness             // uses randomness in synthesis or processing
    - interactions           // defines interactions between audio/visual/text elements
    - other                  // material/process present but not covered above

    2) Environmental interaction  
    How the artwork interacts with its environment. Select all that apply:
    - human_interaction      // input devices: mouse, keyboard, midi, mic, camera, motion sensor, lidar, etc.
    - computer_interaction   // data file, data stream, remote data, web API, etc.
    - none                   // no environmental interaction

    3) Sensory outcomes  
    What the audience perceives, and whether it is static or temporal:
    - modalities: any of [visual, auditory, physical]
    - time: exactly one of [static, time-based] (this is mandatory)

    OUTPUT FORMAT (very important!!):
    Return ONLY a valid JSON object, no extra text, in this exact schema:

    {
    "entities": [
        "processed audio" | "processed image" | "processed text" |
        "synthesized sound" | "synthesized image" | "synthesized text" |
        "randomness" | "interactions" | "other"
    ],
    "interaction": [
        "human interaction" | "computer interaction" | "none"
    ],
    "outcome": [
        "visual" | "auditory" | "physical",
        "static" | "time-based"
    ]
    }

    Follow these rules:
    - Use only the tag strings listed above.
    - The response must be valid JSON and nothing else.

    Now analyze the following source code:
    """,
    version="1.0"
)


PROMPT_2 = PromptTemplate(
    name="detailed_analysis",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed audio"      // uses preexisting audio files
    - "processed image"      // uses preexisting images or video
    - "processed text"       // uses preexisting text or code
    - "synthesized sound"    // generates new sounds or notes
    - "synthesized image"    // generates new visual elements
    - "synthesized text"     // generates new textual/typographic elements
    - "randomness"           // uses randomness in processing or synthesis
    - "interactions"         // defines interactions between audio/visual/text elements
    - "other"

    interaction (exactly 1 if any interaction, otherwise "none"):
    - "human interaction"    // e.g., mouse, keyboard, MIDI, mic, camera, motion sensor, lidar
    - "computer interaction" // e.g., data files, streams, remote data, web APIs
    - "none"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory", "physical"
    - time: "static" or "time-based"

    Rules:
    - Use only the tags listed above.
    - If there is no interaction, use ["none"] for interaction.
    - In "outcome", always include exactly one of "static" or "time-based".

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection",
    version="2.0"
)


PROMPT_3 = PromptTemplate(
    name='roxana-template',
    template=""" 
Given the code below, classify it according to the following framework for generative art analysis.

---

### Framework

**Material and Processes:**
- processed_audio: The code uses pre-existing audio files (e.g., mp3, wav, midi) as input.
- processed_image: The code loads or manipulates already existing images or videos.
- processed_text: The code takes already written texts (e.g., documents, strings) and transforms them.
- synthesized_sound: The code generates new sound algorithmically (e.g., oscillators, generators).
- synthesized_image: The code generates new graphics (e.g., lines, shapes, fractals, shaders).
- synthesized_text: The text is generated by the algorithm (e.g., Markov, GPT, rules).
- randomness: The code uses random functions to influence generation or processing.
- interactions: Internal elements of the system affect each other (e.g., audio -> visual).

**Environmental interaction:**
- human_interaction: The artwork is influenced by human actions(user input) (e.g., mouse clicks, midi controller, microphone, keyboard, camera, motion sensor, touch, lidar, among others).
- computer_interaction: The artwork receives input from external computational sources (APIs, data file, automatic sensors, data stream, remote data, among others).
- none: No external input of any kind.

**Sensory outcomes:**
- visual: produces visual output.
- auditory: produces auditory output.
- physical: produces real physical effects.
- static: the work may animate or react to input, but its overall structure and content do NOT meaningfully progress over time. The scene can loop forever or keep responding to the user, but if you compare the work after a long time with an earlier moment, you are essentially seeing the same kind of state (no accumulation of new elements, no irreversible stages, no narrative timeline). Simple continuous motion (e.g. rotation with frameCount, oscillations, or mouse-based lighting) still counts as "static" for this task.
- time_based: the work clearly unfolds or progresses over time, even if the user does nothing. For example, it accumulates new elements in arrays or lists, reveals new text or images step by step, follows an audio or video timeline, moves through distinct phases, or ends in a state that is systematically different from how it started (e.g. more and more objects appear until a final message is shown). Use "time_based" when the code encodes a temporal narrative, growth, or accumulation.

(Refer to these categories using the **EXACT LABELS** above.)

Important notes:
- In Sensory outcomes, it is mandatory to have **at least one** of "static" or "time_based".

---

### Requirements

1. Read the code.
2. Choose all values that apply to its generative or artistic behavior.
3. Return a structured JSON as follows:

```json
{{
  "material_and_processes": [...],
  "interaction": [...],
  "outcome": [...],
  "explanation": [
    "Concise reasoning referencing variables, libraries, or functions in the code."
  ],
  "reuse_algorithm": "Brief note on algorithm reuse or novelty."
}}

### Code to analyze
""",
    description="Detailed classification with interaction detection",
    version="3.0"
)



PROMPT_4 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed_audio"      // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
    - "processed_image"      // uses preexisting visual material, such as image or video files, as part of the artwork
    - "processed_text"       // uses preexisting textual material, such as text or code files, as part of the artwork
    - "synthesized_sound"    // synthesizes or generates new sounds or notes as part of the artwork
    - "synthesized_image"    // synthesizes or generates new visual elements as part of the artwork
    - "synthesized_text"     // synthesizes or generates new textual or typographic elements as part of the artwork
    - "randomness"           // uses any random function in the synthesis or processing of audio, visual, or textual elements

    interaction (exactly 1):
    - "yes"                  // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar, data files, streams, remote data, or web APIs
    - "no"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory"
    - time: "static" or "time_based" // "static" means that, from a human perspective, the output draw does not change over time. If it changes, it is "time_based".

    Rules:
    - Use only the tags listed above.
    - In "interaction", always include exactly one tag: "yes" or "no".
    - In "outcome", always include exactly one of "static" or "time_based".
    - In "outcome", include one or more applicable modality tags.
    - Do not infer tags that are not supported by the code.

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection - New classification",
    version="4.0"
)



PROMPT_5 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed_audio"      // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
    - "processed_image"      // uses preexisting visual material, such as image or video files, as part of the artwork
    - "processed_text"       // uses preexisting textual material, such as text or code files, as part of the artwork
    - "synthesized_sound"    // synthesizes or generates new sounds or notes as part of the artwork
    - "synthesized_image"    // synthesizes or generates new visual elements (shapes, lines, shaders, particles, typography on screen, image transformations, etc) as part of the artwork
    - "synthesized_text"     // synthesizes or generates new textual or typographic elements as part of the artwork
    - "randomness"           // uses any stochastic, pseudo-random, or noise-based process in the synthesis or processing of visual, auditory, or textual elements. Add this tag whenever the code uses randomness at any stage, even once, including in setup(). This includes random(), randomGaussian(), Math.random(), noise(), randomSeed(), noiseSeed(), shuffle(), probabilistic branching, random selection from arrays, and random initialization of parameters such as position, size, color, timing, velocity, or procedural structure. Seeded randomness still counts. Do not require the result to look chaotic; if random or noise-based values influence the artwork, include "randomness".

    interaction (exactly 1):
    - "yes"                  // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar, data files, streams, remote data, or web APIs
    - "no"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory"
    - time: "static" or "time_based" // "static" means that, from a human perspective, the output draw does not change over time. If it changes, it is "time_based".


    Randomness rule:
    
    - Add "randomness" if the code uses any stochastic or pseudo-random mechanism anywhere in the artwork pipeline.
    - This includes both:
      1. explicit randomness, such as random(), Math.random(), randomGaussian(), shuffle(), probabilistic if/else decisions, random picks from arrays;
      2. procedural randomness, such as noise(), Perlin noise, seeded random/noise, or any random initialization of visual/audio/text parameters.
    - Count it even if:
      - it happens only in setup();
      - the output becomes static afterward;
      - the randomness is seeded and reproducible;
      - it affects only small details rather than the main composition.
    - Do NOT require that the result look chaotic or unpredictable to a human. If random or noise-based values are used in generation, tag "randomness"..

    Rules:
    - Use only the tags listed above.
    - In "interaction", always include exactly one tag: "yes" or "no".
    - In "outcome", always include exactly one of "static" or "time_based".
    - In "outcome", include one or more applicable modality tags.
    - Do not infer tags that are not supported by the code.

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection - New classification",
    version="4.0"
)




PROMPT_10 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You classify p5.js source code and return ONLY a JSON object.

Output format:
{"entities":[],"interaction":[],"outcome":[]}

Rules for output:
- Return valid JSON only.
- No markdown.
- No explanation.
- No extra text before or after the JSON.
- entities: array of 0+ tags
- interaction: array with exactly 1 tag, either "yes" or "no"
- outcome: array with 1+ modality tags and exactly 1 time tag
- If "auditory" is present, "time_based" must also be present

The ONLY allowed tags for each category are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

How to classify

entities
- processed_audio: uses preexisting audio material or live audio input
  Examples: loadSound(), audio files, microphone, audio capture, reading or transforming existing audio
- processed_image: uses preexisting visual material or live visual input
  Examples: loadImage(), image(), createVideo(), video files, webcam, camera, createCapture(VIDEO), reading or transforming existing visual material
- processed_text: uses preexisting textual material
  Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/code/data files
- synthesized_sound: generates new sound or modifies audio in a generative way
  Examples: oscillators, generated notes, algorithmic sound, transforming loaded audio and outputting sound
- synthesized_image: generates or transforms visual output
  Examples: shapes, lines, pixels, shaders, particles, typography on screen, image transformations
- synthesized_text: text or typography is shown/generated as part of the piece
  Examples: text() on screen, letters/words/symbols shown visually, fixed strings shown on screen
- randomness: any randomness appears anywhere in the code
  Examples: random(), noise(), Math.random(), shuffle, probabilistic choice, random seed usage

interaction
Use "yes" if the sketch uses any external input, environmental input, live input, loaded file, or user input.
Examples:
- mouse, keyboard, touch
- microphone, camera, sensors, MIDI
- APIs, remote data, URLs, browser params
- local or remote files loaded as input
Use "no" otherwise.

Important interaction rules:
- loadImage() => interaction yes + processed_image
- loadSound() => interaction yes + processed_audio
- loadJSON(), loadStrings(), loadTable(), loadXML() => interaction yes + processed_text
- microphone input => interaction yes + processed_audio
- camera/webcam/video capture => interaction yes + processed_image

outcome
These are based on human perception of the artwork, not internal code structure.

Modality tags:
- visual: anything human-visible is created or shown
  Examples: shapes, images, animation, text on screen, visible video
- auditory: any audible sound is produced or played
  Examples: music, tones, generated sound, manipulated audio output

Time tag:
- static: the human experience does not vary over time
- time-based: the human experience varies over time visually or auditorily

RANDOMNESS DECISION RULE

Decide the randomness tag BEFORE semantic interpretation.

Search the entire source code for any of these:
- random(
- noise(
- Math.random
- randomSeed
- noiseSeed
- randomGaussian
- shuffle
- random2D

If ANY of them appears anywhere in the code, then entities MUST include "randomness".

Important:
- This includes preload(), setup(), draw(), helper functions, class methods, event handlers, optional branches, and modes.
- This includes randomness used only to choose files, fonts, words, colors, positions, sizes, paths, or parameters.
- This includes Perlin noise via noise(...).
- Do not ask whether the randomness is central, visible, or dominant.
- Presence anywhere in executable code is enough.

TIME-BASED DECISION RULE

Decide "time_based" from the HUMAN EXPERIENCE.

Use "time_based" if a human can see or hear the piece change over runtime, even if:
- the change is caused by mouse, keyboard, sliders, webcam, mic, or other interaction
- the sketch progressively builds an image over frames
- the sketch changes for a while and then stops with noLoop()
- the animation is slow
- the variation is driven by frameCount, millis, noise with a changing time input, random values generated during draw, or variables updated across frames

Use "static" ONLY if the human experience stays visually and auditorily the same over time.

Important:
- A sketch is still "time_based" if it eventually stops after changing.
- A sketch is still "time_based" if the visible change happens only when the user interacts.
- Do NOT classify as "static" just because noLoop() appears somewhere.
- Do NOT classify as "static" just because the piece is interactive rather than autonomous.

Important temporal rules
- Classify by final human experience, not by implementation details alone
- A sketch can be static even if draw() exists
- If it keeps rendering the same still image, use static
- If visuals change over time, use time-based
- If any sound is present, use auditory and time-based

Important inference rules
- Apply all tags that are needed
- A sketch can have both processed and synthesized tags in the same modality
- If text appears on screen, include synthesized_text and visual
- Standard p5.js drawing/rendering usually implies synthesized_image and visual
- If an image is loaded, transformed, and displayed, include processed_image, synthesized_image, visual
- If a song is loaded and played, include processed_audio, auditory, time-based
- If audio is read, transformed, and played, include processed_audio, synthesized_sound, auditory, time-based

Again, the ONLY allowed tags are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

Return only the JSON object using the following template:
    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }
""",
    description="Detailed classification with interaction detection - New classification",
    version="5.0"
)


PROMPT_10a = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You classify p5.js source code and return ONLY a JSON object.

Output format:
{"entities":[],"interaction":[],"outcome":[]}

Rules for output:
- Return valid JSON only.
- No markdown.
- No explanation.
- No extra text before or after the JSON.
- entities: array of 0+ tags
- interaction: array with exactly 1 tag, either "yes" or "no"
- outcome: array with 1+ modality tags and exactly 1 time tag
- If "auditory" is present, "time_based" must also be present

The ONLY allowed tags for each category are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

How to classify

entities
- processed_audio: uses preexisting audio material or live audio input
  Examples: loadSound(), audio files, microphone, audio capture, reading or transforming existing audio
- processed_image: uses preexisting visual material or live visual input
  Examples: loadImage(), image(), createVideo(), video files, webcam, camera, createCapture(VIDEO), reading or transforming existing visual material
- processed_text: uses preexisting textual material
  Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/code/data files
- synthesized_sound: generates new sound or modifies audio in a generative way
  Examples: oscillators, generated notes, algorithmic sound, transforming loaded audio and outputting sound
- synthesized_image: generates or transforms visual output
  Examples: shapes, lines, pixels, shaders, particles, typography on screen, image transformations
- synthesized_text: text or typography is shown/generated as part of the piece
  Examples: text() on screen, letters/words/symbols shown visually, fixed strings shown on screen
- randomness: any randomness appears anywhere in the code
  Examples: random(), noise(), Math.random(), shuffle, probabilistic choice, random seed usage

interaction
Use "yes" if the sketch uses any external input, environmental input, live input, or user input.
Examples:
- mouse, keyboard, touch
- microphone, camera, sensors, MIDI
- APIs, remote data, URLs, browser params
Use "no" otherwise.

Important interaction rules:
- microphone input => interaction yes + processed_audio
- camera/webcam/video capture => interaction yes + processed_image

outcome
These are based on human perception of the artwork, not internal code structure.

Modality tags:
- visual: anything human-visible is created or shown
  Examples: shapes, images, animation, text on screen, visible video
- auditory: any audible sound is produced or played
  Examples: music, tones, generated sound, manipulated audio output

Time tag:
- static: the human experience does not vary over time
- time-based: the human experience varies over time visually or auditorily anywhere in the output

RANDOMNESS DECISION RULE

Decide the randomness tag BEFORE semantic interpretation.

Search the entire source code for any of these:
- random(
- noise(
- Math.random
- randomSeed
- noiseSeed
- randomGaussian
- shuffle
- random2D

If ANY of them appears anywhere in the code, then entities MUST include "randomness".

Important:
- This includes preload(), setup(), draw(), helper functions, class methods, event handlers, optional branches, and modes.
- This includes randomness used only to choose files, fonts, words, colors, positions, sizes, paths, or parameters.
- This includes Perlin noise via noise(...).
- Do not ask whether the randomness is central, visible, or dominant.
- Presence anywhere in executable code is enough.

TIME-BASED DECISION RULE

Decide "time_based" from the HUMAN EXPERIENCE.

Use "time_based" if a human can see or hear the piece change over runtime, even if:
- the change is caused by mouse, keyboard, sliders, webcam, mic, or other interaction
- the sketch progressively builds an image over frames
- the sketch changes for a while and then stops with noLoop()
- the animation is slow
- the variation is driven by frameCount, millis, noise with a changing time input, random values generated during draw, or variables updated across frames
- the variation happens outside the canvas

Use "static" ONLY if the human experience stays visually and auditorily the same over time.

Important:
- A sketch is still "time_based" if it eventually stops after changing.
- A sketch is still "time_based" if the visible change happens only when the user interacts.
- Do NOT classify as "static" just because noLoop() appears somewhere.
- Do NOT classify as "static" just because the piece is interactive rather than autonomous.

Important temporal rules
- Classify by final human experience, not by implementation details alone
- A sketch can be static even if draw() exists
- If it keeps rendering the same still image, use static
- If visuals change over time, use time-based
- If any sound is present, use auditory and time-based

Important inference rules
- Apply all tags that are needed
- A sketch can have both processed and synthesized tags in the same modality
- If generative text appears on screen, include synthesized_text and visual
- Standard p5.js drawing/rendering usually implies synthesized_image and visual
- If an image is loaded, transformed, and displayed, include processed_image, synthesized_image, visual
- If a song is loaded and played, include processed_audio, auditory, time-based
- If audio is read, transformed, and played, include processed_audio, synthesized_sound, auditory, time-based

Again, the ONLY allowed tags are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

Return only the JSON object using the following template:
    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }
""",
    description="Detailed classification with interaction detection - New classification",
    version="5.2"
)


# text false positives
# 


PROMPT_11 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You classify p5.js source code and return ONLY a JSON object.

Output format:
{"entities":[],"interaction":[],"outcome":[]}

Rules for output:
- Return valid JSON only.
- No markdown.
- No explanation.
- No extra text before or after the JSON.
- entities: array of 0+ tags
- interaction: array with exactly 1 tag, either "yes" or "no"
- outcome: array with 1+ modality tags and exactly 1 time tag
- If "auditory" is present, "time_based" must also be present

The ONLY allowed tags for each category are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

How to classify

entities
- processed_audio: uses preexisting audio material or live audio input
  Examples: loadSound(), audio files, microphone, audio capture, reading or transforming existing audio
- processed_image: uses preexisting visual material or live visual input
  Examples: loadImage(), image(), createVideo(), video files, webcam, camera, createCapture(VIDEO), reading or transforming existing visual material
- processed_text: uses preexisting textual material
  Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/code/data files
- synthesized_sound: generates new sound or modifies audio in a generative way
  Examples: oscillators, generated notes, algorithmic sound, transforming loaded audio and outputting sound
- synthesized_image: generates, constructs, arranges, or transforms visual output
  Examples: shapes, lines, pixels, shaders, particles, typography on screen, image transformations, sprites, sprite movement, scrolling backgrounds, spawned objects, collisions, game scenes, visual compositions made from loaded assets
- synthesized_text: text or typography is shown/generated as part of the piece
  Examples: text() on screen, letters/words/symbols shown visually, fixed strings shown on screen
- randomness: any randomness appears anywhere in the code
  Examples: random(), noise(), Math.random(), shuffle, probabilistic choice, random seed usage

interaction
Use "yes" if the sketch uses runtime input, user input, environmental input, live input, browser/page events, or user-triggered console output.

Examples:
- mouse, keyboard, touch
- mouseX, mouseY, mouseIsPressed, keyDown(), keyIsDown()
- mousePressed(), mouseReleased(), keyPressed(), keyTyped(), keyReleased()
- buttons, sliders, input fields, checkboxes, dropdowns
- changed(), input(), mouseOver(), mouseOut()
- file upload, createFileInput(), drag/drop, dropzone
- microphone, camera, sensors, MIDI
- APIs, remote data, URLs, browser params
- windowResized(), windowWidth, windowHeight when used to react to resizing
- console.log() or print() triggered by user/runtime input
- visible DOM/page changes outside the canvas triggered by user/runtime input

Use "no" if the sketch only loads local files once and uses them to create a fixed result.

Important interaction rules:
- loadImage() => processed_image, but not interaction by itself
- loadSound() => processed_audio, but not interaction by itself
- loadJSON(), loadStrings(), loadTable(), loadXML() => processed_text, but not interaction by themselves
- createFileInput(), user-selected files, file drop, or dropzone => interaction yes
- microphone input => interaction yes + processed_audio
- camera/webcam/video capture => interaction yes + processed_image
- console.log() or print() caused by a mouse/key/input/window event => interaction yes, even if the canvas does not change
- visible DOM/page changes outside the canvas caused by user/runtime input => interaction yes

outcome
These are based on human perception of the artwork/page, not internal code structure.

Modality tags:
- visual: anything human-visible is created or shown
  Examples: shapes, images, animation, text on screen, visible video, visible DOM/page elements
- auditory: any audible sound is produced or played
  Examples: music, tones, generated sound, manipulated audio output

Important visual rules:
- The visible page is not limited to the p5 canvas.
- Visible DOM/page changes outside the canvas also count as visual output.
- Examples: createP(), createDiv(), createImg(), createElement(), createA(), style() changes, html() changes.

Time tag:
- static: the human experience does not vary over time
- time_based: the human experience varies over time visually or auditorily

RANDOMNESS DECISION RULE

Decide the randomness tag BEFORE semantic interpretation.

Search the entire source code for any of these:
- random(
- noise(
- Math.random
- randomSeed
- noiseSeed
- randomGaussian
- shuffle
- random2D

If ANY of them appears anywhere in the code, then entities MUST include "randomness".

Important:
- This includes preload(), setup(), draw(), helper functions, class methods, event handlers, optional branches, and modes.
- This includes randomness used only to choose files, fonts, words, colors, positions, sizes, paths, or parameters.
- This includes Perlin noise via noise(...).
- Do not ask whether the randomness is central, visible, or dominant.
- Presence anywhere in executable code is enough.

TIME-BASED DECISION RULE

Decide "time_based" from the HUMAN EXPERIENCE.

Use "time_based" if a human can see or hear the piece change over runtime, even if:
- the change is caused by mouse, keyboard, sliders, webcam, mic, or other interaction
- the visible change happens outside the canvas in DOM/page elements
- the sketch progressively builds an image over frames
- the sketch changes for a while and then stops with noLoop()
- the animation is slow
- the variation is driven by frameCount, millis, noise with a changing time input, random values generated during draw, or variables updated across frames

Use "static" ONLY if the human experience stays visually and auditorily the same over time.

Important:
- A sketch is still "time_based" if it eventually stops after changing.
- A sketch is still "time_based" if the visible change happens only when the user interacts.
- DOM/page changes outside the canvas can make the outcome time_based if they change what the user sees.
- Console output alone does NOT make the outcome visual or time_based, because it is not part of the visible artwork/page.
- Do NOT classify as "static" just because noLoop() appears somewhere.
- Do NOT classify as "static" just because the piece is interactive rather than autonomous.

Important temporal rules
- Classify by final human experience, not by implementation details alone
- A sketch can be static even if draw() exists
- If it keeps rendering the same still image, use static
- If visuals change over time, use time_based
- If any sound is present, use auditory and time_based

Important inference rules
- Apply all tags that are needed
- A sketch can have both processed and synthesized tags in the same modality
- If text appears on screen, include synthesized_text and visual
- Standard p5.js drawing/rendering usually implies synthesized_image and visual
- p5.play sprites, sprite movement, scrolling backgrounds, spawned objects, collisions, and game scenes usually imply synthesized_image and visual
- If an image is loaded and displayed without transformation or composition, include processed_image and visual
- If an image is loaded, transformed, arranged into a scene, or used in a generated visual composition, include processed_image, synthesized_image, and visual
- If a song is loaded and played, include processed_audio, auditory, time_based
- If audio is read, transformed, and played, include processed_audio, synthesized_sound, auditory, time_based

Again, the ONLY allowed tags are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

Return only the JSON object using the following template:
    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }
""",
    description="Detailed classification with interaction detection - New classification",
    version="5.1"
)

# PROMPT_12 = PromptTemplate(
#     name="compact_p5_label_classifier",
#     template="""You classify p5.js source code.

# Return ONLY valid JSON in this format:
# {"entities":[],"interaction":[],"outcome":[]}

# Allowed tags:

# entities:
# - "processed_audio"
# - "processed_image"
# - "processed_text"
# - "synthesized_sound"
# - "synthesized_image"
# - "synthesized_text"
# - "randomness"

# interaction:
# - "yes"
# - "no"

# outcome:
# - "visual"
# - "auditory"
# - "static"
# - "time_based"

# Rules:

# 1. entities

# Use "processed_audio" if the code loads, captures, reads, or uses existing audio.
# Examples: loadSound(), audio files, microphone, audio input.

# Use "processed_image" if the code loads, captures, reads, or uses existing visual media.
# Examples: loadImage(), loadAnimation(), image files, GIFs, video, webcam, createCapture(VIDEO).

# Use "processed_text" if the code loads, reads, or processes existing text/data.
# Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/data files, user-entered text that is processed.

# Use "synthesized_sound" if the code generates or algorithmically modifies sound.
# Examples: oscillators, generated notes, synthesized audio.

# Use "synthesized_image" if the code creates, draws, arranges, transforms, animates, or composes visual output.
# Examples: createCanvas(), draw(), shapes, lines, points, pixels, shaders, images arranged into scenes, sprites, sprite movement, scrolling backgrounds, spawned objects, collisions, games, visual compositions.

# Use "synthesized_text" if visible text is shown or generated for the user.
# Examples: text(), createP(), createDiv(), createA(), createButton() labels, html() text, generated words, visible strings.

# Use "randomness" if executable code contains random behavior.
# Examples: random(), noise(), Math.random(), randomSeed(), noiseSeed(), randomGaussian(), shuffle(), random2D().
# Ignore fully commented-out randomness.

# 2. interaction

# Use "yes" if the sketch uses user input, live input, runtime input, browser/page events, or interactive DOM elements.

# Examples:
# - mouseX, mouseY, mouseIsPressed
# - mousePressed(), mouseReleased(), mouseOver(), mouseOut()
# - keyPressed(), keyTyped(), keyDown(), keyIsDown()
# - buttons, sliders, inputs, checkboxes, dropdowns
# - input(), changed()
# - createFileInput(), drag/drop
# - microphone, webcam, sensors
# - windowResized()
# - remote/API/runtime URL data
# - user-triggered visible DOM/page changes
# - user-triggered console.log() or print()

# Use "no" if the sketch only loads local files once or runs autonomously without user/runtime input.

# Important:
# - loadImage(), loadSound(), loadJSON(), loadStrings(), etc. do NOT imply interaction by themselves.
# - Commented-out interaction does not count.

# 3. outcome modality

# Use "visual" if anything visible is shown on the canvas or page.
# This includes canvas drawings, images, sprites, text, DOM elements, buttons, sliders, paragraphs, links, and visible style/html changes.

# Use "auditory" if any sound is produced or played.
# If "auditory" is present, "time_based" must also be present.

# 4. outcome time

# Use "time_based" if the human-visible or audible experience can change after the initial render.

# This includes changes caused by:
# - draw() changing variables over frames
# - frameCount, millis, timers, intervals
# - movement, velocity, animation, GIF/video playback
# - random/noise values over time
# - mouse, keyboard, buttons, sliders, inputs, dropdowns
# - mouseOver(), mouseOut(), mousePressed(), keyPressed(), input(), changed()
# - DOM/page changes such as createP(), createImg(), html(), style(), added elements
# - sketches that build progressively and then stop
# - sketches with noLoop() that still visibly change before stopping or after interaction

# Use "static" ONLY if the human-visible and audible experience cannot change after the initial result.

# Critical checks before answering:

# - If the code uses createCanvas(), draw(), shapes, sprites, game scenes, image composition, movement, collisions, or generated visuals, include "synthesized_image".
# - Do not return only "processed_image" for games, sprite scenes, composed images, or generated drawings.
# - If interaction="yes" and the interaction changes anything visible or audible, outcome must include "time_based", not "static".
# - If visible DOM/page content changes after interaction, outcome must include "visual" and "time_based".
# - Console output alone does not make outcome visual or time_based.
# - Ignore fully commented-out code.
# - Return exactly one interaction tag: either "yes" or "no".
# - Return exactly one time tag: either "static" or "time_based".

# Return only the JSON object.
# """,
#     description="Compact p5.js classification prompt with strong final checks",
#     version="6.0"
# )

PROMPT_12 = PromptTemplate(
    name="compact_p5_label_classifier_strict_randomness",
    template="""You classify p5.js source code.

Return ONLY valid JSON in this format:
{"entities":[],"interaction":[],"outcome":[]}

Allowed tags:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

Rules:

1. entities

Use "processed_audio" if the code loads, captures, reads, or uses existing audio.
Examples: loadSound(), audio files, microphone, audio input.

Use "processed_image" if the code loads, captures, reads, or uses existing visual media.
Examples: loadImage(), loadAnimation(), image files, GIFs, video, webcam, createCapture(VIDEO).

Use "processed_text" if the code loads, reads, or processes existing text/data.
Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/data files, user-entered text that is processed.

Use "synthesized_sound" if the code generates or algorithmically modifies sound.
Examples: oscillators, generated notes, synthesized audio.

Use "synthesized_image" if the code creates, draws, arranges, transforms, animates, or composes visual output.
Examples: createCanvas(), draw(), shapes, lines, points, pixels, shaders, images arranged into scenes, sprites, sprite movement, scrolling backgrounds, spawned objects, collisions, games, visual compositions.

Use "synthesized_text" if visible text is shown or generated for the user.
Examples: text(), createP(), createDiv(), createA(), createButton() labels, html() text, generated words, visible strings.

Use "randomness" if executable code contains ANY randomness anywhere.

Decide the randomness tag BEFORE semantic interpretation.

Search the entire executable source code for any of these:
- random(
- noise(
- Math.random
- randomSeed
- noiseSeed
- randomGaussian
- shuffle
- random2D

If ANY of them appears anywhere in executable code, entities MUST include "randomness".

Important randomness rules:
- This includes preload(), setup(), draw(), helper functions, class methods, event handlers, optional branches, and modes.
- This includes randomness used only to choose files, fonts, words, colors, positions, sizes, paths, images, sounds, text, or parameters.
- This includes Perlin noise via noise(...).
- Do not ask whether the randomness is central, visible, artistic, dominant, or important.
- Do not ask whether the randomness affects the final visible result.
- Presence anywhere in executable code is enough.
- Ignore fully commented-out randomness.

2. interaction

Use "yes" if the sketch uses user input, live input, runtime input, browser/page events, or interactive DOM elements.

Examples:
- mouseX, mouseY, mouseIsPressed
- mousePressed(), mouseReleased(), mouseOver(), mouseOut()
- keyPressed(), keyTyped(), keyDown(), keyIsDown()
- buttons, sliders, inputs, checkboxes, dropdowns
- input(), changed()
- createFileInput(), drag/drop
- microphone, webcam, sensors
- windowResized()
- remote/API/runtime URL data
- user-triggered visible DOM/page changes
- user-triggered console.log() or print()

Use "no" if the sketch only loads local files once or runs autonomously without user/runtime input.

Important:
- loadImage(), loadSound(), loadJSON(), loadStrings(), etc. do NOT imply interaction by themselves.
- Commented-out interaction does not count.

3. outcome modality

Use "visual" if anything visible is shown on the canvas or page.
This includes canvas drawings, images, sprites, text, DOM elements, buttons, sliders, paragraphs, links, and visible style/html changes.

Use "auditory" if any sound is produced or played.
If "auditory" is present, "time_based" must also be present.

4. outcome time

Use "time_based" if the human-visible or audible experience can change after the initial render.

This includes changes caused by:
- draw() changing variables over frames
- frameCount, millis, timers, intervals
- movement, velocity, animation, GIF/video playback
- random/noise values over time
- mouse, keyboard, buttons, sliders, inputs, dropdowns
- mouseOver(), mouseOut(), mousePressed(), keyPressed(), input(), changed()
- DOM/page changes such as createP(), createImg(), html(), style(), added elements
- sketches that build progressively and then stop
- sketches with noLoop() that still visibly change before stopping or after interaction

Use "static" ONLY if the human-visible and audible experience cannot change after the initial result.

Critical checks before answering:

- If executable code contains random(), noise(), Math.random, randomSeed, noiseSeed, randomGaussian, shuffle, or random2D anywhere, include "randomness", even if it is not central or not visibly obvious.
- If the code uses createCanvas(), draw(), shapes, sprites, game scenes, image composition, movement, collisions, or generated visuals, include "synthesized_image".
- Do not return only "processed_image" for games, sprite scenes, composed images, or generated drawings.
- If interaction="yes" and the interaction changes anything visible or audible, outcome must include "time_based", not "static".
- If visible DOM/page content changes after interaction, outcome must include "visual" and "time_based".
- Console output alone does not make outcome visual or time_based.
- Ignore fully commented-out code.
- Return exactly one interaction tag: either "yes" or "no".
- Return exactly one time tag: either "static" or "time_based".

Return only the JSON object.
""",
    description="Compact p5.js classification prompt with strict randomness detection",
    version="6.1"
)