from dataclasses import dataclass
from typing import Optional

@dataclass
class PromptTemplate:
    name: str
    template: str
    version: Optional[str] = None
    description: Optional[str] = None

# Then define your prompts
PROMPT_1 = PromptTemplate(
    name="basic_classification",
    template="""You are given the source code of a generative artwork (sound, visual, or textual).  
    Using the framework below, tag the artwork along 3 dimensions.

    1) Entities  
    Select all that apply:
    - processed audio        // uses existing audio (e.g., mp3, wav, midi)
    - processed image        // uses existing visual media (e.g., images, video)
    - processed text         // uses existing text/code files
    - synthesized sound      // generates new sounds or notes
    - synthesized image      // generates new visual elements
    - synthesized text       // generates new textual or typographic elements
    - randomness             // uses randomness in synthesis or processing
    - interactions           // defines interactions between audio/visual/text elements
    - other                  // material/process present but not covered above

    2) Environmental interaction  
    How the artwork interacts with its environment. Select all that apply:
    - human_interaction      // input devices: mouse, keyboard, midi, mic, camera, motion sensor, lidar, etc.
    - computer_interaction   // data file, data stream, remote data, web API, etc.
    - none                   // no environmental interaction

    3) Sensory outcomes  
    What the audience perceives, and whether it is static or temporal:
    - modalities: any of [visual, auditory, physical]
    - time: exactly one of [static, time-based] (this is mandatory)

    OUTPUT FORMAT (very important!!):
    Return ONLY a valid JSON object, no extra text, in this exact schema:

    {
    "entities": [
        "processed audio" | "processed image" | "processed text" |
        "synthesized sound" | "synthesized image" | "synthesized text" |
        "randomness" | "interactions" | "other"
    ],
    "interaction": [
        "human interaction" | "computer interaction" | "none"
    ],
    "outcome": [
        "visual" | "auditory" | "physical",
        "static" | "time-based"
    ]
    }

    Follow these rules:
    - Use only the tag strings listed above.
    - The response must be valid JSON and nothing else.

    Now analyze the following source code:
    """,
    version="1.0"
)


PROMPT_2 = PromptTemplate(
    name="detailed_analysis",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed audio"      // uses preexisting audio files
    - "processed image"      // uses preexisting images or video
    - "processed text"       // uses preexisting text or code
    - "synthesized sound"    // generates new sounds or notes
    - "synthesized image"    // generates new visual elements
    - "synthesized text"     // generates new textual/typographic elements
    - "randomness"           // uses randomness in processing or synthesis
    - "interactions"         // defines interactions between audio/visual/text elements
    - "other"

    interaction (exactly 1 if any interaction, otherwise "none"):
    - "human interaction"    // e.g., mouse, keyboard, MIDI, mic, camera, motion sensor, lidar
    - "computer interaction" // e.g., data files, streams, remote data, web APIs
    - "none"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory", "physical"
    - time: "static" or "time-based"

    Rules:
    - Use only the tags listed above.
    - If there is no interaction, use ["none"] for interaction.
    - In "outcome", always include exactly one of "static" or "time-based".

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection",
    version="2.0"
)


PROMPT_3 = PromptTemplate(
    name='roxana-template',
    template=""" 
Given the code below, classify it according to the following framework for generative art analysis.

---

### Framework

**Material and Processes:**
- processed_audio: The code uses pre-existing audio files (e.g., mp3, wav, midi) as input.
- processed_image: The code loads or manipulates already existing images or videos.
- processed_text: The code takes already written texts (e.g., documents, strings) and transforms them.
- synthesized_sound: The code generates new sound algorithmically (e.g., oscillators, generators).
- synthesized_image: The code generates new graphics (e.g., lines, shapes, fractals, shaders).
- synthesized_text: The text is generated by the algorithm (e.g., Markov, GPT, rules).
- randomness: The code uses random functions to influence generation or processing.
- interactions: Internal elements of the system affect each other (e.g., audio -> visual).

**Environmental interaction:**
- human_interaction: The artwork is influenced by human actions(user input) (e.g., mouse clicks, midi controller, microphone, keyboard, camera, motion sensor, touch, lidar, among others).
- computer_interaction: The artwork receives input from external computational sources (APIs, data file, automatic sensors, data stream, remote data, among others).
- none: No external input of any kind.

**Sensory outcomes:**
- visual: produces visual output.
- auditory: produces auditory output.
- physical: produces real physical effects.
- static: the work may animate or react to input, but its overall structure and content do NOT meaningfully progress over time. The scene can loop forever or keep responding to the user, but if you compare the work after a long time with an earlier moment, you are essentially seeing the same kind of state (no accumulation of new elements, no irreversible stages, no narrative timeline). Simple continuous motion (e.g. rotation with frameCount, oscillations, or mouse-based lighting) still counts as "static" for this task.
- time_based: the work clearly unfolds or progresses over time, even if the user does nothing. For example, it accumulates new elements in arrays or lists, reveals new text or images step by step, follows an audio or video timeline, moves through distinct phases, or ends in a state that is systematically different from how it started (e.g. more and more objects appear until a final message is shown). Use "time_based" when the code encodes a temporal narrative, growth, or accumulation.

(Refer to these categories using the **EXACT LABELS** above.)

Important notes:
- In Sensory outcomes, it is mandatory to have **at least one** of "static" or "time_based".

---

### Requirements

1. Read the code.
2. Choose all values that apply to its generative or artistic behavior.
3. Return a structured JSON as follows:

```json
{{
  "material_and_processes": [...],
  "interaction": [...],
  "outcome": [...],
  "explanation": [
    "Concise reasoning referencing variables, libraries, or functions in the code."
  ],
  "reuse_algorithm": "Brief note on algorithm reuse or novelty."
}}

### Code to analyze
""",
    description="Detailed classification with interaction detection",
    version="3.0"
)



PROMPT_4 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed_audio"      // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
    - "processed_image"      // uses preexisting visual material, such as image or video files, as part of the artwork
    - "processed_text"       // uses preexisting textual material, such as text or code files, as part of the artwork
    - "synthesized_sound"    // synthesizes or generates new sounds or notes as part of the artwork
    - "synthesized_image"    // synthesizes or generates new visual elements as part of the artwork
    - "synthesized_text"     // synthesizes or generates new textual or typographic elements as part of the artwork
    - "randomness"           // uses any random function in the synthesis or processing of audio, visual, or textual elements

    interaction (exactly 1):
    - "yes"                  // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar, data files, streams, remote data, or web APIs
    - "no"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory"
    - time: "static" or "time_based" // "static" means that, from a human perspective, the output draw does not change over time. If it changes, it is "time_based".

    Rules:
    - Use only the tags listed above.
    - In "interaction", always include exactly one tag: "yes" or "no".
    - In "outcome", always include exactly one of "static" or "time_based".
    - In "outcome", include one or more applicable modality tags.
    - Do not infer tags that are not supported by the code.

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection - New classification",
    version="4.0"
)


PROMPT_5 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You are an expert in generative art in p5.js, and you are going to analyse a source code of a generative artwork in p5.js and output tags in JSON.

The ONLY dimensions and allowed tags are:

---

entities (0+ tags):

- "processed_audio" // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
- "processed_image" // uses preexisting visual material, such as image or video files, as part of the artwork
- "processed_text" // uses preexisting textual material, such as text or code files, as part of the artwork
- "randomness"

interaction (exactly 1):

- "yes" // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar. Reading data files, streams, remote data, or web APIs also counts as interactions.
- "no" // if the artwork does not include interactions (or if the only interaction is to save images)

outcome (≥1 modality + 1 time tag):

- "visual" // Add "visual" modality whenever the code draws or renders anything, meaning it produces something you can see.
- "auditory" // Add "auditory" modality whenever the code generates, plays, records, or analyzes sound (p5.sound/Web Audio/MIDI/mic/audio files); it can be both if it does any drawing and any audio.
- "text" // adds text or typographic elements as part of the artwork
- "static" or "time_based" // exactly 1 time tag. "static" means that, from a human perspective, the output draw does not change over time (even if draw() loops). "time_based" means the rendered output changes over time.

---

Time tag rule (summary):

- If noLoop() is present OR draw() is absent → time tag = "static".
- Else → time tag = "time_based" ONLY if something forces visible change across frames (e.g., frameCount/millis/deltaTime used in drawing, per-frame state updates, random/noise evaluated in draw(), or live input affecting drawing). Otherwise → "static".


Overall Rules:

- You are only allowed to use the tags listed above. Do not create new tags.
- In "interaction", always include exactly one tag: "yes" or "no".
- In "outcome", always include exactly one of "static" or "time_based".
- In "outcome", include one or more applicable modality tags.
- Do not infer tags that are not supported by the code.

Output format (JSON only, no explanation, no extra text):

{
"entities": [...],
"interaction": [...],
"outcome": [...]
}

Now analyze this source code:
""",
    description="Detailed classification with interaction detection - New classification",
    version="5.0"
)