from dataclasses import dataclass
from typing import Optional

@dataclass
class PromptTemplate:
    name: str
    template: str
    version: Optional[str] = None
    description: Optional[str] = None

# Then define your prompts
PROMPT_1 = PromptTemplate(
    name="basic_classification",
    template="""You are given the source code of a generative artwork (sound, visual, or textual).  
    Using the framework below, tag the artwork along 3 dimensions.

    1) Entities  
    Select all that apply:
    - processed audio        // uses existing audio (e.g., mp3, wav, midi)
    - processed image        // uses existing visual media (e.g., images, video)
    - processed text         // uses existing text/code files
    - synthesized sound      // generates new sounds or notes
    - synthesized image      // generates new visual elements
    - synthesized text       // generates new textual or typographic elements
    - randomness             // uses randomness in synthesis or processing
    - interactions           // defines interactions between audio/visual/text elements
    - other                  // material/process present but not covered above

    2) Environmental interaction  
    How the artwork interacts with its environment. Select all that apply:
    - human_interaction      // input devices: mouse, keyboard, midi, mic, camera, motion sensor, lidar, etc.
    - computer_interaction   // data file, data stream, remote data, web API, etc.
    - none                   // no environmental interaction

    3) Sensory outcomes  
    What the audience perceives, and whether it is static or temporal:
    - modalities: any of [visual, auditory, physical]
    - time: exactly one of [static, time-based] (this is mandatory)

    OUTPUT FORMAT (very important!!):
    Return ONLY a valid JSON object, no extra text, in this exact schema:

    {
    "entities": [
        "processed audio" | "processed image" | "processed text" |
        "synthesized sound" | "synthesized image" | "synthesized text" |
        "randomness" | "interactions" | "other"
    ],
    "interaction": [
        "human interaction" | "computer interaction" | "none"
    ],
    "outcome": [
        "visual" | "auditory" | "physical",
        "static" | "time-based"
    ]
    }

    Follow these rules:
    - Use only the tag strings listed above.
    - The response must be valid JSON and nothing else.

    Now analyze the following source code:
    """,
    version="1.0"
)


PROMPT_2 = PromptTemplate(
    name="detailed_analysis",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed audio"      // uses preexisting audio files
    - "processed image"      // uses preexisting images or video
    - "processed text"       // uses preexisting text or code
    - "synthesized sound"    // generates new sounds or notes
    - "synthesized image"    // generates new visual elements
    - "synthesized text"     // generates new textual/typographic elements
    - "randomness"           // uses randomness in processing or synthesis
    - "interactions"         // defines interactions between audio/visual/text elements
    - "other"

    interaction (exactly 1 if any interaction, otherwise "none"):
    - "human interaction"    // e.g., mouse, keyboard, MIDI, mic, camera, motion sensor, lidar
    - "computer interaction" // e.g., data files, streams, remote data, web APIs
    - "none"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory", "physical"
    - time: "static" or "time-based"

    Rules:
    - Use only the tags listed above.
    - If there is no interaction, use ["none"] for interaction.
    - In "outcome", always include exactly one of "static" or "time-based".

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection",
    version="2.0"
)


PROMPT_3 = PromptTemplate(
    name='roxana-template',
    template=""" 
Given the code below, classify it according to the following framework for generative art analysis.

---

### Framework

**Material and Processes:**
- processed_audio: The code uses pre-existing audio files (e.g., mp3, wav, midi) as input.
- processed_image: The code loads or manipulates already existing images or videos.
- processed_text: The code takes already written texts (e.g., documents, strings) and transforms them.
- synthesized_sound: The code generates new sound algorithmically (e.g., oscillators, generators).
- synthesized_image: The code generates new graphics (e.g., lines, shapes, fractals, shaders).
- synthesized_text: The text is generated by the algorithm (e.g., Markov, GPT, rules).
- randomness: The code uses random functions to influence generation or processing.
- interactions: Internal elements of the system affect each other (e.g., audio -> visual).

**Environmental interaction:**
- human_interaction: The artwork is influenced by human actions(user input) (e.g., mouse clicks, midi controller, microphone, keyboard, camera, motion sensor, touch, lidar, among others).
- computer_interaction: The artwork receives input from external computational sources (APIs, data file, automatic sensors, data stream, remote data, among others).
- none: No external input of any kind.

**Sensory outcomes:**
- visual: produces visual output.
- auditory: produces auditory output.
- physical: produces real physical effects.
- static: the work may animate or react to input, but its overall structure and content do NOT meaningfully progress over time. The scene can loop forever or keep responding to the user, but if you compare the work after a long time with an earlier moment, you are essentially seeing the same kind of state (no accumulation of new elements, no irreversible stages, no narrative timeline). Simple continuous motion (e.g. rotation with frameCount, oscillations, or mouse-based lighting) still counts as "static" for this task.
- time_based: the work clearly unfolds or progresses over time, even if the user does nothing. For example, it accumulates new elements in arrays or lists, reveals new text or images step by step, follows an audio or video timeline, moves through distinct phases, or ends in a state that is systematically different from how it started (e.g. more and more objects appear until a final message is shown). Use "time_based" when the code encodes a temporal narrative, growth, or accumulation.

(Refer to these categories using the **EXACT LABELS** above.)

Important notes:
- In Sensory outcomes, it is mandatory to have **at least one** of "static" or "time_based".

---

### Requirements

1. Read the code.
2. Choose all values that apply to its generative or artistic behavior.
3. Return a structured JSON as follows:

```json
{{
  "material_and_processes": [...],
  "interaction": [...],
  "outcome": [...],
  "explanation": [
    "Concise reasoning referencing variables, libraries, or functions in the code."
  ],
  "reuse_algorithm": "Brief note on algorithm reuse or novelty."
}}

### Code to analyze
""",
    description="Detailed classification with interaction detection",
    version="3.0"
)



PROMPT_4 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed_audio"      // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
    - "processed_image"      // uses preexisting visual material, such as image or video files, as part of the artwork
    - "processed_text"       // uses preexisting textual material, such as text or code files, as part of the artwork
    - "synthesized_sound"    // synthesizes or generates new sounds or notes as part of the artwork
    - "synthesized_image"    // synthesizes or generates new visual elements as part of the artwork
    - "synthesized_text"     // synthesizes or generates new textual or typographic elements as part of the artwork
    - "randomness"           // uses any random function in the synthesis or processing of audio, visual, or textual elements

    interaction (exactly 1):
    - "yes"                  // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar, data files, streams, remote data, or web APIs
    - "no"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory"
    - time: "static" or "time_based" // "static" means that, from a human perspective, the output draw does not change over time. If it changes, it is "time_based".

    Rules:
    - Use only the tags listed above.
    - In "interaction", always include exactly one tag: "yes" or "no".
    - In "outcome", always include exactly one of "static" or "time_based".
    - In "outcome", include one or more applicable modality tags.
    - Do not infer tags that are not supported by the code.

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection - New classification",
    version="4.0"
)



PROMPT_5 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You analyze source code of a generative artwork and output tags in JSON.

    Dimensions and allowed tags:

    entities (0+ tags):
    - "processed_audio"      // uses preexisting audio material, such as mp3, wav, or MIDI files, as part of the artwork
    - "processed_image"      // uses preexisting visual material, such as image or video files, as part of the artwork
    - "processed_text"       // uses preexisting textual material, such as text or code files, as part of the artwork
    - "synthesized_sound"    // synthesizes or generates new sounds or notes as part of the artwork
    - "synthesized_image"    // synthesizes or generates new visual elements (shapes, lines, shaders, particles, typography on screen, image transformations, etc) as part of the artwork
    - "synthesized_text"     // synthesizes or generates new textual or typographic elements as part of the artwork
    - "randomness"           // uses any stochastic, pseudo-random, or noise-based process in the synthesis or processing of visual, auditory, or textual elements. Add this tag whenever the code uses randomness at any stage, even once, including in setup(). This includes random(), randomGaussian(), Math.random(), noise(), randomSeed(), noiseSeed(), shuffle(), probabilistic branching, random selection from arrays, and random initialization of parameters such as position, size, color, timing, velocity, or procedural structure. Seeded randomness still counts. Do not require the result to look chaotic; if random or noise-based values influence the artwork, include "randomness".

    interaction (exactly 1):
    - "yes"                  // the artwork includes interaction, such as mouse, keyboard, MIDI, mic, camera, motion sensor, lidar, data files, streams, remote data, or web APIs
    - "no"

    outcome (≥1 modality + exactly 1 time tag):
    - modalities: "visual", "auditory"
    - time: "static" or "time_based" // "static" means that, from a human perspective, the output draw does not change over time. If it changes, it is "time_based".


    Randomness rule:
    
    - Add "randomness" if the code uses any stochastic or pseudo-random mechanism anywhere in the artwork pipeline.
    - This includes both:
      1. explicit randomness, such as random(), Math.random(), randomGaussian(), shuffle(), probabilistic if/else decisions, random picks from arrays;
      2. procedural randomness, such as noise(), Perlin noise, seeded random/noise, or any random initialization of visual/audio/text parameters.
    - Count it even if:
      - it happens only in setup();
      - the output becomes static afterward;
      - the randomness is seeded and reproducible;
      - it affects only small details rather than the main composition.
    - Do NOT require that the result look chaotic or unpredictable to a human. If random or noise-based values are used in generation, tag "randomness"..

    Rules:
    - Use only the tags listed above.
    - In "interaction", always include exactly one tag: "yes" or "no".
    - In "outcome", always include exactly one of "static" or "time_based".
    - In "outcome", include one or more applicable modality tags.
    - Do not infer tags that are not supported by the code.

    Output format (JSON only, no explanation, no extra text):

    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }

    Now analyze this source code:
    """,
    description="Detailed classification with interaction detection - New classification",
    version="4.0"
)




PROMPT_10 = PromptTemplate(
    name="detailed_analysis_new_categories",
    template="""You classify p5.js source code and return ONLY a JSON object.

Output format:
{"entities":[],"interaction":[],"outcome":[]}

Rules for output:
- Return valid JSON only.
- No markdown.
- No explanation.
- No extra text before or after the JSON.
- entities: array of 0+ tags
- interaction: array with exactly 1 tag, either "yes" or "no"
- outcome: array with 1+ modality tags and exactly 1 time tag
- If "auditory" is present, "time_based" must also be present

The ONLY allowed tags for each category are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

How to classify

entities
- processed_audio: uses preexisting audio material or live audio input
  Examples: loadSound(), audio files, microphone, audio capture, reading or transforming existing audio
- processed_image: uses preexisting visual material or live visual input
  Examples: loadImage(), image(), createVideo(), video files, webcam, camera, createCapture(VIDEO), reading or transforming existing visual material
- processed_text: uses preexisting textual material
  Examples: loadJSON(), loadStrings(), loadTable(), loadXML(), external text/code/data files
- synthesized_sound: generates new sound or modifies audio in a generative way
  Examples: oscillators, generated notes, algorithmic sound, transforming loaded audio and outputting sound
- synthesized_image: generates or transforms visual output
  Examples: shapes, lines, pixels, shaders, particles, typography on screen, image transformations
- synthesized_text: text or typography is shown/generated as part of the piece
  Examples: text() on screen, letters/words/symbols shown visually, fixed strings shown on screen
- randomness: any randomness appears anywhere in the code
  Examples: random(), noise(), Math.random(), shuffle, probabilistic choice, random seed usage

interaction
Use "yes" if the sketch uses any external input, environmental input, live input, loaded file, or user input.
Examples:
- mouse, keyboard, touch
- microphone, camera, sensors, MIDI
- APIs, remote data, URLs, browser params
- local or remote files loaded as input
Use "no" otherwise.

Important interaction rules:
- loadImage() => interaction yes + processed_image
- loadSound() => interaction yes + processed_audio
- loadJSON(), loadStrings(), loadTable(), loadXML() => interaction yes + processed_text
- microphone input => interaction yes + processed_audio
- camera/webcam/video capture => interaction yes + processed_image

outcome
These are based on human perception of the artwork, not internal code structure.

Modality tags:
- visual: anything human-visible is created or shown
  Examples: shapes, images, animation, text on screen, visible video
- auditory: any audible sound is produced or played
  Examples: music, tones, generated sound, manipulated audio output

Time tag:
- static: the human experience does not vary over time
- time-based: the human experience varies over time visually or auditorily

RANDOMNESS DECISION RULE

Decide the randomness tag BEFORE semantic interpretation.

Search the entire source code for any of these:
- random(
- noise(
- Math.random
- randomSeed
- noiseSeed
- randomGaussian
- shuffle
- random2D

If ANY of them appears anywhere in the code, then entities MUST include "randomness".

Important:
- This includes preload(), setup(), draw(), helper functions, class methods, event handlers, optional branches, and modes.
- This includes randomness used only to choose files, fonts, words, colors, positions, sizes, paths, or parameters.
- This includes Perlin noise via noise(...).
- Do not ask whether the randomness is central, visible, or dominant.
- Presence anywhere in executable code is enough.

TIME-BASED DECISION RULE

Decide "time_based" from the HUMAN EXPERIENCE.

Use "time_based" if a human can see or hear the piece change over runtime, even if:
- the change is caused by mouse, keyboard, sliders, webcam, mic, or other interaction
- the sketch progressively builds an image over frames
- the sketch changes for a while and then stops with noLoop()
- the animation is slow
- the variation is driven by frameCount, millis, noise with a changing time input, random values generated during draw, or variables updated across frames

Use "static" ONLY if the human experience stays visually and auditorily the same over time.

Important:
- A sketch is still "time_based" if it eventually stops after changing.
- A sketch is still "time_based" if the visible change happens only when the user interacts.
- Do NOT classify as "static" just because noLoop() appears somewhere.
- Do NOT classify as "static" just because the piece is interactive rather than autonomous.

Important temporal rules
- Classify by final human experience, not by implementation details alone
- A sketch can be static even if draw() exists
- If it keeps rendering the same still image, use static
- If visuals change over time, use time-based
- If any sound is present, use auditory and time-based

Important inference rules
- Apply all tags that are needed
- A sketch can have both processed and synthesized tags in the same modality
- If text appears on screen, include synthesized_text and visual
- Standard p5.js drawing/rendering usually implies synthesized_image and visual
- If an image is loaded, transformed, and displayed, include processed_image, synthesized_image, visual
- If a song is loaded and played, include processed_audio, auditory, time-based
- If audio is read, transformed, and played, include processed_audio, synthesized_sound, auditory, time-based

Again, the ONLY allowed tags are:

entities:
- "processed_audio"
- "processed_image"
- "processed_text"
- "synthesized_sound"
- "synthesized_image"
- "synthesized_text"
- "randomness"

interaction:
- "yes"
- "no"

outcome:
- "visual"
- "auditory"
- "static"
- "time_based"

Return only the JSON object using the following template:
    {
    "entities": [...],
    "interaction": [...],
    "outcome": [...]
    }
""",
    description="Detailed classification with interaction detection - New classification",
    version="5.0"
)

# text false positives
# 